version: '3'
services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./config:/etc/traefik/config
      - ./_wildcard.localhost.development.pem:/etc/traefik/_wildcard.localhost.development.pem
      - ./_wildcard.localhost.development-key.pem:/etc/traefik/_wildcard.localhost.development-key.pem
    # extra_hosts is only needed if you're using WSL2 on Windows
    # to find the ip, open a WSL terminal and run "ip addr show eth0"
#    extra_hosts:
#      - "gateway.docker.internal:172.20.8.220"
