version: '3'
services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
      - "8099:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config:/etc/traefik/config:ro
      - ./_wildcard.localhost.test.pem:/etc/traefik/_wildcard.localhost.test.pem:ro
      - ./_wildcard.localhost.test-key.pem:/etc/traefik/_wildcard.localhost.test-key.pem:ro
    # extra_hosts is only needed if you're using Docker without Docker Desktop
    # https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
