version: '3'
services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
      - "8099:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config:/etc/traefik/config:ro
      - ./_wildcard.localhost.test.pem:/etc/traefik/_wildcard.localhost.test.pem:ro
      - ./_wildcard.localhost.test-key.pem:/etc/traefik/_wildcard.localhost.test-key.pem:ro
    # extra_hosts is only needed if you're using WSL2 on Windows
    # to find the ip, open a WSL terminal and run "ip addr show eth0"
#    extra_hosts:
#      - "gateway.docker.internal:172.20.10.112"
