version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "8070:8070"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./_wildcard.dev.localhost.crt:/etc/nginx/_wildcard.dev.localhost.crt
      - ./_wildcard.dev.localhost.key:/etc/nginx/_wildcard.dev.localhost.key
      - ./_wildcard.dev.localhost.pem:/etc/nginx/_wildcard.dev.localhost.pem
      - ./_wildcard.dev.localhost-key.pem:/etc/nginx/_wildcard.dev.localhost-key.pem
    extra_hosts:
      - "gateway.docker.internal:172.30.252.211"
